name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: UEFI
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  WERROR: 1

jobs:

  build-linux:
    name: 使用自建Linux构建
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          file="clang+llvm-9.0.1-x86_64-linux-gnu-ubuntu-16.04"
          suf=".tar.xz"
          curl -LO "https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/${file}${suf}" || exit 1
          sum=$(shasum -a 256 "${file}${suf}" | cut -f1 -d' ')
          expsum="1af280e96fec62acf5f3bb525e36baafe09f95f940dc9806e22809a83dfff4f8"
          if [ "$sum" != "$expsum" ]; then echo "Invalid checksum $sum" ; exit 1 ; fi
          tar -xf "${file}${suf}" || exit 1
          echo "$(pwd)//bin" >> 
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/wy414012/ocbuild/yaming/ci-bootstrap.sh) && eval "$src" || exit 1 

      - run: ./build_oc.tool

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linux CLANGPDB-GCC5 Artifacts
          path: Binaries/*.zip
